"""candle_m1, feed_outage, candle_revision

Revision ID: 4e728592724f
Revises: 683fa06efdfd
Create Date: 2026-09-28 15:31:02.085648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e728592724f"
down_revision: Union[str, Sequence[str], None] = "683fa06efdfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candle_m1",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ts_open", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("ask_close", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("tick_volume", sa.Integer(), nullable=True),
        sa.Column(
            "backfilled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "date_trunc('minute', ts_open) = ts_open",
            name=op.f("ck_candle_m1_minute_pleine"),
        ),
        sa.CheckConstraint(
            "low <= least(open, close) AND high >= greatest(open, close)",
            name=op.f("ck_candle_m1_ohlc_coherent"),
        ),
        sa.PrimaryKeyConstraint("source", "ts_open", name=op.f("pk_candle_m1")),
    )
    op.create_table(
        "feed_outage",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cause", sa.Text(), nullable=False),
        sa.Column("closed_reason", sa.Text(), nullable=True),
        sa.Column(
            "bars_backfilled", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.CheckConstraint(
            "cause IN ('timeout', 'erreur_api', 'reseau', 'auth', 'limite_api', 'donnees_absentes')",
            name=op.f("ck_feed_outage_cause"),
        ),
        sa.CheckConstraint(
            "closed_reason IS NULL OR closed_reason IN ('retour_flux', 'fermeture_marche')",
            name=op.f("ck_feed_outage_closed_reason"),
        ),
        sa.CheckConstraint(
            "(ended_at IS NULL) = (closed_reason IS NULL)",
            name=op.f("ck_feed_outage_fermeture_complete"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_outage")),
    )
    op.create_index(
        "uq_feed_outage_source_ouverte",
        "feed_outage",
        ["source"],
        unique=True,
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.create_table(
        "candle_revision",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("ts_open", sa.DateTime(timezone=True), nullable=False),
        sa.Column("champ", sa.Text(), nullable=False),
        sa.Column("valeur_stockee", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("valeur_recue", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "champ IN ('open', 'high', 'low', 'close')",
            name=op.f("ck_candle_revision_champ"),
        ),
        sa.ForeignKeyConstraint(
            ["source", "ts_open"],
            ["candle_m1.source", "candle_m1.ts_open"],
            name=op.f("fk_candle_revision_source_candle_m1"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candle_revision")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candle_revision")
    op.drop_index(
        "uq_feed_outage_source_ouverte",
        table_name="feed_outage",
        postgresql_where=sa.text("ended_at IS NULL"),
    )
    op.drop_table("feed_outage")
    op.drop_table("candle_m1")
    # ### end Alembic commands ###
